[feat] ArraySubsetAssertion
zenstruck/assert pull request #14
Opened 2022-06-28 17:10 UTC by nikophil

2022-06-29 13:11 UTC, kbond requested changes

2022-06-29 13:11 UTC, kbond commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +        if (!\is_countable($haystack) && !\is_iterable($haystack)) {
This is not required assuming you meant for the `array` typehint above?

2022-06-29 13:11 UTC, kbond commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +    /** @var iterable|\Countable */
Assuming this should only be an array, we should use `array`.

2022-06-29 13:11 UTC, kbond commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +     * @param string|null $message Available context: {expected}, {actual}, {haystack}
Just `{needle}` & `{haystack}` here?

2022-06-29 13:11 UTC, kbond commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +        ];
```suggestion
        return [
            'needle' => $this->needle,
            'haystack' => $this->haystack,
        ];
```

2022-06-29 13:11 UTC, kbond commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +        $this->arrayIsList($needle) ? sort($needle) : ksort($needle);
We can use the native array_is_list() function (it was added in PHP 8 but we require the polyfill).

2022-06-29 13:11 UTC, kbond commented on tests/Assertion/ArraySubsetAssertionTest.php
> +        );
Should be equivalent.

```suggestion
        Assert::run(new ArraySubsetAssertion($needle, $haystack));
```

2022-06-29 13:11 UTC, kbond commented on tests/Assertion/ArraySubsetAssertionTest.php
> +        Assert::fail('nop');
This should be equivalent.

```suggestion
        Assert::not(new ArraySubsetAssertion($needle, $haystack));
```

2022-07-01 14:28 UTC, nikophil commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +    }
I'm not convinced the arrays should be printed out. It makes sense for small arrays, but not anymore with big ones (ie: json api outputs :shrug: )

2022-07-01 14:54 UTC, nikophil commented on README.md
> +Assert::that(['foo' => [1,2,3]])->isSubsetOf(['foo' => [1,2,3], 'bar' => 'foo']); // pass
I don't really know the best way to explain this...
actually user should not "slice" lists in array/json:

a more "real life" example would be:
```json
{
    "users" : [
        {
            "name": "user 1"
        },
        {
            "name": "user 2"
        },
        {
            "name": "user 3"
        }
    ]
}
```
has not the following has subset, although we would expect it to be a subset:
```json
{
    "users" : [
        {
            "name": "user 2"
        }
    ]
}

```

2022-07-01 14:54 UTC, nikophil commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +    }
even if we expose `needle` and `haystack` in the context, I'm not convinced they should be printed out in the output... It would make sense for small arrays, but not for big ones (ie: api response... :shrug:)

2022-07-01 14:54 UTC, nikophil commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +    }
BTW, I don't really like names `needle` and `haystack` in the output, but I can't find better ones (and these names are common in php src...)

2022-07-01 14:54 UTC, nikophil commented on src/Assert/Expectation.php
> +    }
I think we need to revert it, because when it will be used with browser's `Json` it should be inverted:
```
(new Json('{"foo" => "bar", "bar" => "foo"}')->hasSubset(['foo' => 'bar']);
```

2022-07-01 14:54 UTC, nikophil commented on src/Assert/Expectation.php
> +    }
But this makes me think we should somehow override this method in browser's`Json` (or at list create some other methods) in order to be able to provide json directly.

Maybe we should think now about the usage of this assertion in `zenstruck/browser`?

A propositions could be:
```php
// Json

public function containsJson(string|Json $json): self;
```

or maybe we should handle json strings directly in `ArraySubsetAssertion`? WDYT?

2022-07-01 15:09 UTC, nikophil commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +        return $this->haystack === \array_replace_recursive($this->haystack, $this->needle);
it's funny how simple is the implementation :sweat_smile:

2022-07-07 12:48 UTC, kbond reviewed
Really like this implementation!

2022-07-07 12:48 UTC, kbond commented on README.md
> +Assert::that(['foo' => [1,2,3]])->isSubsetOf(['foo' => [1,2,3], 'bar' => 'foo']); // pass
Does this implementation have the same behaviour as PHPUnit's old method and API Platform (your above real life example would fail)? If so, I'm ok with this.

However, I agree your real life example looks like a common assertion a user would make. How realistic do you think a follow-up PR that supports array lists is?

2022-07-07 12:48 UTC, kbond commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +    }
> even if we expose needle and haystack in the context, I'm not convinced they should be printed out in the output... It would make sense for small arrays, but not for big ones (ie: api response... shrug)

They will be converted to `(array)` in the message so probably doesn't add much value anyway.

With the `PHPUnitHandler` and `--verbose` the context will be output in full (I think) below the failing test message.

> BTW, I don't really like names needle and haystack in the output, but I can't find better ones (and these names are common in php src, so I decided to keep them...)

Yeah, can't think of a better name either....

2022-07-07 12:48 UTC, kbond commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +        if ($iterable instanceof \ArrayObject) {
_sorry :)_

```suggestion
        }

        if ($iterable instanceof \ArrayObject) {
```

2022-07-07 13:01 UTC, kbond commented on src/Assert/Expectation.php
> +    public function isSubsetOf(iterable $expected, ?string $message = null, array $context = []): self
```suggestion
    /**
     * @param string|null $message Available context: {needle}, {haystack}
     */
    public function isSubsetOf(iterable $expected, ?string $message = null, array $context = []): self
```

2022-07-07 13:02 UTC, kbond commented on src/Assert/Expectation.php
> +    public function hasSubset(iterable $expected, ?string $message = null, array $context = []): self
```suggestion
    /**
     * @param string|null $message Available context: {needle}, {haystack}
     */
    public function hasSubset(iterable $expected, ?string $message = null, array $context = []): self
```

2022-07-07 13:43 UTC, kbond requested changes
We should add the _not_ assertions to `Expectation`: `Expectation::notHasSubset()` & `IsNotSubsetOf()`.

For allowing json strings, what about leaving `ArraySubsetAssertion` as-is and having the Expectation method's allow json strings and decode?

2022-07-11 08:34 UTC, nikophil commented on README.md
> +Assert::that(['foo' => [1,2,3]])->isSubsetOf(['foo' => [1,2,3], 'bar' => 'foo']); // pass
> Does this implementation have the same behaviour as PHPUnit's old method and API Platform (your above real life example would fail)? If so, I'm ok with this.

this implementation is ~stolen~ heavily inspired from phpunit's one, so yes, it has the same behavior than this one and the example I gave would fail.

> However, I agree your real life example looks like a common assertion a user would make. How realistic do you think a follow-up PR that supports array lists is?

nothing is impossible :innocent: but I don't think we could rely on `array_replace_recursive()` for this.

2022-07-11 08:37 UTC, nikophil commented on src/Assert/Assertion/ArraySubsetAssertion.php
> +    }
ok then I think I can close this

2022-07-11 08:39 UTC, nikophil commented on src/Assert/Expectation.php
> +    }
> > or maybe we should handle json strings directly in ArraySubsetAssertion? WDYT?

> I'd be fine with this.

ok then I think we need to merge #15 in oprder to leverage `Type::jsonString()`

2022-07-11 09:22 UTC, nikophil commented
> We should add the not assertions to Expectation: Expectation::notHasSubset() & IsNotSubsetOf().
done

> For allowing json strings, what about leaving ArraySubsetAssertion as-is and having the Expectation method's allow json strings and decode?
I'd rather do it inside `ArraySubsetAssertion` because we already have a private method `toArray` that we apply on both needle and haystack. this would prevent to add a method specific to array subsets inside `Expectation` class

2022-07-11 15:40 UTC, kbond approved these changes

2022-07-11 15:40 UTC, merged